ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;

      rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  tls:
    - hosts:
      - nc.corno.dev
      secretName: nextcloud-tls
  hosts:
  - nc.corno.dev
nextcloud:
  host: nc.corno.dev
  extraEnv:
    - name: OVERWRITEPROTOCOL
      value: https
  mail:
    enabled: true
    fromAddress: dave
    domain: corno.co.uk
    smtp:
      host: smtp.gmail.com
      secure: ssl
      port: 465
      authtype: LOGIN
      name: dave@corno.co.uk


postgresql:
  enabled: true
  persistence:
    enabled: true
    storageClass: csi-lvm-sc-mirror

persistence:
  # Nextcloud Data (/var/www/html)
  enabled: true
  storageClass: csi-lvm-sc-mirror
  accessMode: ReadWriteOnce
  size: 100Gi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: nc-postgresql-0.nc-postgresql-headless.prod.svc.cluster.local
  user: nextcloud
